### ISSUE TITLE
Nome de Interface

### ISSUE THREAD

**Issue by fredroo** [loiane/curso-angular#195]
qual a boa prática para nome de interface, tanto o nome do arquivo como o nome da interface

vi que usam IProduct por exemplo para uma interface de product como convenção, mas no ionic por exemplo não se usa nome de arquivo maiúsculo, como ficaria o nome do arquivo @loiane e estou certo ficar algo como `export interface IProduct`

**Comment by loiane** [comment]
Olá, no Angular não usamos o prefixo, isso é mais pra linguagens de backend.
