### ISSUE TITLE
problema com o loadChildren lo lazy loading

### ISSUE THREAD

**Issue by mzramna** [loiane/curso-angular#298]
nas versões mais atuais do angular o loadChildren tem que ser feito da seguinte forma:
`loadChildren:() => import('./cursos/cursos.module').then(mod=>mod.CursosModule),title:"cursos"`
deve ser passado também a importação como era anteriormente, mas agora a definição de qual classe usada é passada com uma arrow function e não com o sharp
caso seja passado da forma como foi ensinado no curso o vscode retorna o seguinte erro:
`O tipo 'string' não pode ser atribuído ao tipo 'LoadChildrenCallback'.ts(2322)
index.d.ts(2447, 5): O tipo esperado vem da propriedade 'loadChildren', que é declarada aqui no tipo 'Route'`

**Comment by loiane** [comment]
Olá, nas aulas mais recentes atualizados o código pra usar a nova sintaxe do angular.
