### ISSUE TITLE
Incluir Swagger ao projeto

### ISSUE THREAD

**Issue by diegotopow** [loiane/curso-angular#358]
Olá a todos, tudo bem?
Estive buscando uma forma de integrar o Swagger a este projeto, como forma de aprendizado e estudos, contudo ainda não consegui, nem fazer as configurações básicas, muito menos a UI da ferramenta.
Será que alguém poderia me ajudar quando à configuração, pois as dependências já foram inseridas.
Muito obrigado a todos e Deus abençoe.

**Comment by NGS-Adryan** [comment]
tentou ver com o chat-gpt?
salva vidas kkk

**Comment by loiane** [comment]
@diegotopow o projeto tem Open API habilitado: https://github.com/loiane/crud-angular-spring
