### ISSUE TITLE
Quando alterar a detecção padrão de mudanças do Angular?

### ISSUE THREAD

**Issue by renebentes** [loiane/curso-angular#60]
Boas, Loiane, tudo bem?

Primeiro quero lhe agradecer por compartilhar conhecimento, está sendo de grande ajuda.

Googlando por aí, encontrei bibliotecas que modificam a detecção padrão do Angular para OnPush e outras não, algumas até com muitos downloads. Pergunto em que momento isso realmente é necessário, sei que há uma melhoria de performance justificável, mas gostaria realmente de compreender o mecanismo e aplicabilidade.

Se puder exemplificar, agradeço...

Mas uma vez obrigado.

**Rene Bentes Pinto**

**Comment by danilodomingos** [comment]
Boa tarde, me junto ao amigo.

Recentemente venho trabalhando num projeto Angular e percebi q a cada
momento ele fica registrando os eventos.
Seria uma boa prática mudar esse comportamento?
