### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by ArthurFuchsReis** [loiane/curso-angular#76]
Olá Loiane, tudo bem? Estou fazendo o seu curso e estou usando o atual angular 10.

No entanto, alguma recursos que você usou no passado(na época da gravação), não me permite fazer hoje.  Eu precisei fazer umas modificações.

E na hora de ver o resultado, no vídeo gravado o seu resultado aparece com sucesso, o meu não.

Já tentei permancer com avisos e deixar identico ao seu, mas mesmo assim não mostra o resultado como esperado.

Tem como a senhora me ajudar com essas mudanças para eu obter o resultado igual ao seu, por favor?

Att,

@ArthurFuchsReis

**Comment by loiane** [comment]
Oi @ArthurFuchsReis vc chegou a comparar o código aqui do github com o o seu? Infelizmente não irei regravar vídeos antigos pois são muitos (rs), mas sempre mantenho os código aqui atualizado - inclusive estou para atualizar para a versão 10.

**Comment by ArthurFuchsReis** [comment]
@loiane 

Não fiz não, pois eu pensava que estava com formato desatualizado também.

Mas vou fazer isso sim.

Obrigado.

P.S: Você é a melhor professora de Angular.
