### ISSUE TITLE
erro em contrução de componente

### ISSUE THREAD

**Issue by ArthurFuchsReis** [loiane/curso-angular#84]
Bom dia Loiane, tudo bem?

Bom, estou na aula 60 do seu curso, e fui incluir o componente alunos como foi solicitado no video. 

e me apareceu a seguinte mensagem:

C:\Users\arfur\OneDrive\Desktop\Treinamento Loiane 2\rotas>ng g c alunos
Your global Angular CLI version (10.0.2) is greater than your local
version (10.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
More than one module matches. Use the skip-import option to skip importing the component into the closest module or use the module option to specify a module.

C:\Users\arfur\OneDrive\Desktop\Treinamento Loiane 2\rotas>**ng config -g cli.warnings.versionMismatch false**
Your global Angular CLI version (10.0.2) is greater than your local
version (10.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

C:\Users\arfur\OneDrive\Desktop\Treinamento Loiane 2\rotas>**ng g c alunos**
More than one module matches. Use the skip-import option to skip importing the component into the closest module or use the module option to specify a module.

como devo proceder?

Att,

@ArthurFuchsReis

**Comment by AlanBessa** [comment]
Arthur,
A instalação do seu Angular CLI local é mais nova que a sua local. Isso não é um erro, somente um alerta. O que vc pode fazer é atualizar sua versão de Angular CLI localmente ( sem o uso do -g), se vc quiser.

**Comment by ArthurFuchsReis** [comment]
@AlanBessa Obrigado

**Comment by ArthurFuchsReis** [comment]
@AlanBessa Eu fiz o que você disse, e deu certo, mas ao criar o componente pelo cli, me aparece a seguinte mensagem:

C:\Users\arfur\OneDrive\Desktop\Treinamento Loiane 2\rotas>ng g c alunos
More than one module matches. Use the skip-import option to skip importing the component into the closest module or use the module option to specify a module.
