### ISSUE TITLE
Problemas com Property/Event Binding

### ISSUE THREAD

**Issue by Renato-Afonso** [loiane/curso-angular#94]
Eu tentei aplicar o código "<input type="text" [value] = "title" (keyup.enter) = "title =$event.target.value"/>", mas um erro SEMPRE ocorre...meu prompt de comando fica dizendo: 

Object is possibly 'null'.
 
(keyup.enter) = "title =$event.target.value"/>   

E também  

Property 'value' does not exist on type 'EventTarget'.
 
(keyup.enter) = "title =$event.target.value"/>; 

Eu segui as orientações da aula à risca, o que estou fazendo de errado? Por acaso preciso adicionar outras linhas de código ou tem outro addon que eu precise fazer o download?

**Comment by loiane** [comment]
@Renato-Afonso o angular agora é mais restrito em relação a isso.
Tente o seguinte, isso vai checar por null:
"title =$event?.target?.value"

**Comment by Renato-Afonso** [comment]
Opa muito obrigado, vou tentar sim 😀👍

Em seg, 7 de dez de 2020 19:07, Loiane Groner <notifications@github.com>
escreveu:

**Comment by tonhozi** [comment]
Na versão 12 isso não resolve. Tente o seguinte:
`$any($event.target).value`
